<style>
    #nette-debug .nette-mailChimpPanel,
    #tracy-debug .nette-mailChimpPanel { min-width: 700px; }
    #nette-debug .nette-mailChimpPanel table,
    #tracy-debug .nette-mailChimpPanel table { width: 100%; }
    #tracy-debug .nette-mailChimpPanel h2 { font-weight: bold; font-size: 18px; }
</style>

<div class="nette-inner tracy-inner nette-mailChimpPanel">
    <?php foreach($this->resources as $resource): ?>
        <h2>
            <?php echo $esc(strtoupper((string) $resource->request->getMethod())); ?>
            <?php echo $esc((string) $resource->request->getUri()); ?>
            STATUS: <?php echo $esc((string) $resource->status); ?>
        </h2>
        <table>
            <tr><th>Time</th><td><?php echo $esc(number_format($resource->time * 1000, 2, '.', ' ')) ?>&nbsp;ms</td></tr>
            <tr><th>Request</th><td><?php echo $click($resource->request, TRUE); ?></td></tr>
            <tr><th>Response</th><td><?php echo $click($resource->response ?: $resource->exception, TRUE); ?></td></tr>
            <tr><th>Result</th><td><?php echo $click($resource->result, TRUE); ?></td></tr>
        </table>
    <?php endforeach; ?>
</div>